import "@/styles/reset.css";
import "@/styles/global.css";
import { Be_Vietnam_Pro } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Manage Landing Page",
  description: "Generated by create next app",
  creator: "Sertac Can",
  keywords: ["Next.js", "React", "JavaScript"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={beVietnamPro.className}>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
